In [3]:
import numpy as np
from numpy import genfromtxt

In [4]:
data=genfromtxt('C:/Users/GOWTHAM/Downloads/bank_note_data.txt',delimiter=',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [6]:
labels=data[:,4]

In [7]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [8]:
features=data[:,0:4]

In [9]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [10]:
x=features
y=labels

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [13]:
from sklearn.preprocessing import MinMaxScaler

In [14]:
scaler_object=MinMaxScaler()

In [15]:
scaler_object.fit(x_train)

MinMaxScaler()

In [16]:
scaled_x_train=scaler_object.transform(x_train)

In [17]:
scaled_x_test=scaler_object.transform(x_test)

In [18]:
scaled_x_train.max()

np.float64(1.0000000000000002)

In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [26]:
model=Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(4,activation='relu'))

model.add(Dense(1,activation='sigmoid'))

In [27]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [28]:
model.fit(scaled_x_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 1s - 31ms/step - accuracy: 0.5734 - loss: 0.6634
Epoch 2/50
29/29 - 0s - 2ms/step - accuracy: 0.5919 - loss: 0.6588
Epoch 3/50
29/29 - 0s - 2ms/step - accuracy: 0.6246 - loss: 0.6537
Epoch 4/50
29/29 - 0s - 2ms/step - accuracy: 0.6333 - loss: 0.6479
Epoch 5/50
29/29 - 0s - 2ms/step - accuracy: 0.6474 - loss: 0.6422
Epoch 6/50
29/29 - 0s - 2ms/step - accuracy: 0.6638 - loss: 0.6354
Epoch 7/50
29/29 - 0s - 2ms/step - accuracy: 0.6551 - loss: 0.6267
Epoch 8/50
29/29 - 0s - 2ms/step - accuracy: 0.6507 - loss: 0.6187
Epoch 9/50
29/29 - 0s - 2ms/step - accuracy: 0.6442 - loss: 0.6109
Epoch 10/50
29/29 - 0s - 2ms/step - accuracy: 0.6529 - loss: 0.6025
Epoch 11/50
29/29 - 0s - 2ms/step - accuracy: 0.6670 - loss: 0.5946
Epoch 12/50
29/29 - 0s - 2ms/step - accuracy: 0.6670 - loss: 0.5861
Epoch 13/50
29/29 - 0s - 2ms/step - accuracy: 0.6855 - loss: 0.5776
Epoch 14/50
29/29 - 0s - 2ms/step - accuracy: 0.6910 - loss: 0.5696
Epoch 15/50
29/29 - 0s - 3ms/step - accuracy: 0.7301 - l

In [32]:
predict=model.predict(scaled_x_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 


In [33]:
from sklearn.metrics import confusion_matrix,classification_report

In [39]:
predict_labels=(predict>0.5).astype(int)

confusion_matrix(y_test,predict_labels)

array([[249,   8],
       [ 34, 162]])

In [42]:
print(classification_report(y_test,predict_labels))

              precision    recall  f1-score   support

         0.0       0.88      0.97      0.92       257
         1.0       0.95      0.83      0.89       196

    accuracy                           0.91       453
   macro avg       0.92      0.90      0.90       453
weighted avg       0.91      0.91      0.91       453



In [44]:
model.save('bank_note_autenticate_model.keras')

In [45]:
from keras.models import load_model

In [46]:
newmodel=load_model('bank_note_autenticate_model.keras')

C:\Users\GOWTHAM\OneDrive\Desktop\tfframework\OpenCV\Lib\site-packages\keras\src\saving\saving_lib.py:757: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 8 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [48]:
newmodel.predict(scaled_x_test)

15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


array([[0.1419425 ],
       [0.33635113],
       [0.3002025 ],
       [0.2693537 ],
       [0.07765558],
       [0.08980701],
       [0.23741549],
       [0.04655022],
       [0.09058249],
       [0.19862813],
       [0.32956862],
       [0.6134412 ],
       [0.37362555],
       [0.7960199 ],
       [0.6150714 ],
       [0.2409072 ],
       [0.7746471 ],
       [0.7788186 ],
       [0.94911224],
       [0.7480758 ],
       [0.06953526],
       [0.18504311],
       [0.7262927 ],
       [0.04603888],
       [0.92464507],
       [0.05279131],
       [0.05776978],
       [0.80913234],
       [0.02494085],
       [0.03231514],
       [0.56559545],
       [0.21041825],
       [0.28215933],
       [0.94348174],
       [0.88112646],
       [0.04578216],
       [0.3111926 ],
       [0.56593907],
       [0.65870345],
       [0.1861527 ],
       [0.22865285],
       [0.5760443 ],
       [0.55460227],
       [0.07723875],
       [0.8708632 ],
       [0.88232255],
       [0.80507094],
       [0.155